/// debug_view_monsters()
i = 60;
xpos = 4;
debug_draw_var2("MONSTERS", "", xpos);
i += 1;
debug_draw_var2("Area 0:", "", xpos);
i -= 1;
debug_draw_var2("X", global.metdead[0], xpos + 40);
i -= 1;
i += 1;
debug_draw_var2("Area 1:", "", xpos);
i -= 1;
debug_draw_var2("X", global.metdead[1], xpos + 40);
i -= 1;
debug_draw_var2("X", global.metdead[2], xpos + 50);
i -= 1;
debug_draw_var2("X", global.metdead[3], xpos + 60);
i -= 1;
debug_draw_var2("X", global.metdead[4], xpos + 70);
i -= 1;
i += 1;
debug_draw_var2("Area 2:", "", xpos);
i -= 1;
debug_draw_var2("X", global.metdead[5], xpos + 40);
i -= 1;
debug_draw_var2("X", global.metdead[6], xpos + 50);
i -= 1;
debug_draw_var2("X", global.metdead[7], xpos + 60);
i -= 1;
debug_draw_var2("X", global.metdead[8], xpos + 70);
i -= 1;
debug_draw_var2("X", global.metdead[9], xpos + 80);
i -= 1;
debug_draw_var2("X", global.metdead[10], xpos + 90);
i -= 1;
debug_draw_var2("X", global.metdead[11], xpos + 100);
i -= 1;
debug_draw_var2("X", global.metdead[12], xpos + 110);
i -= 1;
i += 1;
debug_draw_var2("Area 3:", "", xpos);
i -= 1;
debug_draw_var2("X", global.metdead[13], xpos + 40);
i -= 1;
debug_draw_var2("X", global.metdead[14], xpos + 50);
i -= 1;
debug_draw_var2("X", global.metdead[15], xpos + 60);
i -= 1;
debug_draw_var2("X", global.metdead[16], xpos + 70);
i -= 1;
debug_draw_var2("X", global.metdead[17], xpos + 80);
i -= 1;
debug_draw_var2("X", global.metdead[18], xpos + 90);
i -= 1;
debug_draw_var2("X", global.metdead[19], xpos + 100);
i -= 1;
debug_draw_var2("X", global.metdead[20], xpos + 110);
i -= 1;
debug_draw_var2("X", global.metdead[21], xpos + 120);
i -= 1;
debug_draw_var2("X", global.metdead[22], xpos + 130);
i -= 1;
i += 1;
debug_draw_var2("Area 3A:", "", xpos);
i -= 1;
debug_draw_var2("X", global.metdead[23], xpos + 40);
i -= 1;
debug_draw_var2("X", global.metdead[24], xpos + 50);
i -= 1;
debug_draw_var2("X", global.metdead[25], xpos + 60);
i -= 1;
debug_draw_var2("X", global.metdead[26], xpos + 70);
i -= 1;
i += 1;
debug_draw_var2("Area 4:", "", xpos);
i -= 1;
debug_draw_var2("X", global.metdead[27], xpos + 40);
i -= 1;
debug_draw_var2("X", global.metdead[28], xpos + 50);
i -= 1;
debug_draw_var2("X", global.metdead[29], xpos + 60);
i -= 1;
debug_draw_var2("X", global.metdead[30], xpos + 70);
i -= 1;
debug_draw_var2("X", global.metdead[31], xpos + 80);
i -= 1;
debug_draw_var2("X", global.metdead[32], xpos + 90);
i -= 1;
i += 1;
debug_draw_var2("Area 5:", "", xpos);
i -= 1;
debug_draw_var2("X", global.metdead[33], xpos + 40);
i -= 1;
debug_draw_var2("X", global.metdead[34], xpos + 50);
i -= 1;
debug_draw_var2("X", global.metdead[35], xpos + 60);
i -= 1;
debug_draw_var2("X", global.metdead[36], xpos + 70);
i -= 1;
debug_draw_var2("X", global.metdead[37], xpos + 80);
i -= 1;
debug_draw_var2("X", global.metdead[38], xpos + 90);
i -= 1;
debug_draw_var2("X", global.metdead[39], xpos + 100);
i -= 1;
debug_draw_var2("X", global.metdead[40], xpos + 110);
i -= 1;
i += 1;
debug_draw_var2("Area 6:", "", xpos);
i -= 1;
debug_draw_var2("X", global.metdead[41], xpos + 40);
i -= 1;
debug_draw_var2("X", global.metdead[42], xpos + 50);
i -= 1;
debug_draw_var2("X", global.metdead[43], xpos + 60);
i -= 1;
debug_draw_var2("X", global.metdead[44], xpos + 70);
i -= 1;
debug_draw_var2("X", global.metdead[45], xpos + 80);
i -= 1;
i += 1;
debug_draw_var2("Area 7:", "", xpos);
i -= 1;
debug_draw_var2("X", global.metdead[46], xpos + 40);
i -= 1;
debug_draw_var2("X", global.metdead[47], xpos + 50);
i -= 1;
debug_draw_var2("X", global.metdead[48], xpos + 60);
i -= 1;
debug_draw_var2("X", global.metdead[49], xpos + 70);
i -= 1;
debug_draw_var2("X", global.metdead[50], xpos + 80);
i -= 1;
debug_draw_var2("X", global.metdead[51], xpos + 90);
i -= 1;
debug_draw_var2("X", global.metdead[52], xpos + 100);
i -= 1;
debug_draw_var2("X", global.metdead[53], xpos + 110);
i -= 1;
debug_draw_var2("X", global.metdead[54], xpos + 120);
i -= 1;
