/// Unmute_Loops()
audio_resume_sound(sndSpinJump);
audio_sound_gain(sndSpinJump, global.opsoundvolume / 100, 0);
audio_resume_sound(sndSpaceJump);
audio_sound_gain(sndSpaceJump, global.opsoundvolume / 100, 0);
audio_resume_sound(sndScrewAttack);
audio_sound_gain(sndScrewAttack, global.opsoundvolume / 100, 0);
audio_resume_sound(sndSpaceScrewAttack);
audio_sound_gain(sndSpaceScrewAttack, global.opsoundvolume / 100, 0);
audio_resume_sound(sndSpinJumpWater);
audio_sound_gain(sndSpinJumpWater, global.opsoundvolume / 100, 0);
audio_resume_sound(sndSBStart);
audio_sound_gain(sndSBStart, global.opsoundvolume / 100, 0);
audio_resume_sound(sndSBLoop);
audio_sound_gain(sndSBLoop, global.opsoundvolume / 100, 0);
audio_resume_sound(sndSBChargeLoop);
audio_sound_gain(sndSBChargeLoop, global.opsoundvolume / 100, 0);
audio_resume_sound(sndSJLoop);
audio_sound_gain(sndSJLoop, global.opsoundvolume / 100, 0);
audio_resume_sound(sndSBallLoop);
audio_sound_gain(sndSBallLoop, global.opsoundvolume / 100, 0);
audio_resume_sound(sndCharge);
audio_sound_gain(sndCharge, global.opsoundvolume / 100, 0);
audio_resume_sound(sndChargeLoop);
audio_sound_gain(sndChargeLoop, global.opsoundvolume / 100, 0);
audio_resume_sound(sndLavaLoop);
audio_sound_gain(sndLavaLoop, global.opsoundvolume / 100, 0);
audio_resume_sound(sndPlantLoop);
audio_sound_gain(sndPlantLoop, global.opsoundvolume / 100, 0);
audio_resume_sound(sndA2WJLoop);
audio_sound_gain(sndA2WJLoop, global.opsoundvolume / 100, 0);
audio_resume_sound(sndQuakeLoop);
audio_sound_gain(sndQuakeLoop, global.opsoundvolume / 100, 0);
audio_resume_sound(sndMGammaElecLoop);
audio_sound_gain(sndMGammaElecLoop, global.opsoundvolume / 100, 0);
audio_resume_sound(sndALLaserLoop);
audio_sound_gain(sndALLaserLoop, global.opsoundvolume / 100, 0);
audio_resume_sound(sndALBladesLoop);
audio_sound_gain(sndALBladesLoop, global.opsoundvolume / 100, 0);
audio_resume_sound(sndMachineLoop1);
audio_sound_gain(sndMachineLoop1, global.opsoundvolume / 100, 0);
audio_resume_sound(sndDrillLoop);
audio_sound_gain(sndDrillLoop, global.opsoundvolume / 100, 0);
audio_resume_sound(sndStoneLoop);
audio_sound_gain(sndStoneLoop, global.opsoundvolume / 100, 0);
audio_resume_sound(sndA4AlarmLoop);
audio_sound_gain(sndA4AlarmLoop, global.opsoundvolume / 100, 0);
audio_resume_sound(sndTesterMeleeLoop);
audio_sound_gain(sndTesterMeleeLoop, global.opsoundvolume / 100, 0);
audio_resume_sound(sndElevatorLoop);
audio_sound_gain(sndElevatorLoop, global.opsoundvolume / 100, 0);
audio_resume_sound(sndDrainLoop);
audio_sound_gain(sndDrainLoop, global.opsoundvolume / 100, 0);
audio_resume_sound(sndWaterfallLoop);
audio_sound_gain(sndWaterfallLoop, global.opsoundvolume / 100, 0);
audio_resume_sound(sndGFTrooperBattleLoop);
audio_sound_gain(sndGFTrooperBattleLoop, global.opsoundvolume / 100, 0);
audio_resume_sound(sndLowEnergyAlertLoop); 
audio_sound_gain(sndLowEnergyAlertLoop, global.opsoundvolume / 100, 0);
audio_resume_sound(sndSBEris); 
audio_sound_gain(sndSBEris, global.opsoundvolume / 100, 0);
